#!/bin/sh
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. "$DIR/config"

echo =====
echo Creating cluster ${CLUSTER_NAME} with ${NUM_NODES} nodes ...
echo =====

gcloud container clusters create ${CLUSTER_NAME} --num-nodes=${NUM_NODES}
gcloud compute instances list

echo
echo =====
echo Creating pod for ${IMAGE_NAME}
echo =====
kubectl run ${DEPLOYMENT_NAME} --image=gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION} --port 80
kubectl get pods
