#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. "$DIR/config"
IMAGE_VERSION=`cat VERSION`

echo =====
echo Creating docker image ${IMAGE_NAME}:${IMAGE_VERSION} ...
echo =====

# Go to parent directory
pushd "${DIR}/.."

IMAGE_VERSION=`cat VERSION`

docker build -t gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION} .

popd
