#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. "$DIR/config"

echo =====
echo Creating docker image ${IMAGE_NAME}:${IMAGE_VERSION} ...
echo =====

# Go to parent directory
pushd "${DIR}/.."

docker build -t gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION} .

popd
