#!/bin/sh
#
# Deploy the updated Docker image to the Google Cloud

. ./gcloud/config

echo =====
echo Creating Fat JAR ...
echo =====

mvn package -Dmaven.test.skip=true

echo
echo =====
echo Bumping version ...
echo =====

VERSION=`cat VERSION`
VERSION=`echo ${VERSION} | ./gcloud/inc.awk`
echo ${VERSION} > VERSION
echo Version: ${VERSION}

echo
echo =====
echo Pushing Version to GitHub ...
echo =====

git add VERSION
git commit -m "Version ${VERSION}"
git tag -a "${VERSION}" -m "Version ${VERSION}"
git push
git push --tags

echo
echo =====
echo Building docker image ...
echo =====

docker build -t gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${VERSION} .

echo
echo =====
echo Pushing docker image to Google Cloud ...
echo =====
gcloud docker -- push gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${VERSION}

echo
echo =====
echo Activating deployed container ...
echo =====
kubectl set image deployment/${DEPLOYMENT_NAME} ${DEPLOYMENT_NAME}=gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${VERSION}
