#!/bin/sh
#
# Deploy the updated Docker image to the Google Cloud

. ./gcloud/config

mvn package -Dmaven.test.skip=true

echo =====
echo Building docker image ...
echo =====

docker build -t gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION} .

echo
echo =====
echo Pushing docker image to Google Cloud ...
echo =====
gcloud docker -- push gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION}

echo
echo =====
echo Activating deployed container ...
echo =====
kubectl set image deployment/${DEPLOYMENT_NAME} ${DEPLOYMENT_NAME}=gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION}
