#!/bin/sh
#
# Deploy the updated Docker image to the Google Cloud

mvn package -Dmaven.test.skip=true

echo
echo =====
echo
ls -l target
echo
echo =====
echo

docker build -t gcr.io/aircraftnoise100/aircraft-noise-recorder:v9 .
gcloud docker -- push gcr.io/aircraftnoise100/aircraft-noise-recorder:v9
kubectl set image deployment/aircraft-noise-recorder-pod aircraft-noise-recorder-pod=gcr.io/aircraftnoise100/aircraft-noise-recorder:v9
