#!/bin/sh
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. "$DIR/config"

echo =====
echo De-allocating load balancer
echo =====

kubectl delete service ${DEPLOYMENT_NAME}

echo
echo =====
echo Waiting until the load balancer is deleted
echo =====

NUM_FORWARDING_RULES=-1
while [ "$NUM_FORWARDING_RULES" != "0" ]; do
  NUM_FORWARDING_RULES=`gcloud compute forwarding-rules list 2>&1 | grep -E "Listed\ \d+\ items." | sed -E -n 's/.*\ ([0-9]+)\ .*/\1/p'`
  echo Currently $NUM_FORWARDING_RULES forwarding rules are active.
done

echo
echo =====
echo Deleting container cluster
echo =====

gcloud container clusters delete ${CLUSTER_NAME}
