#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. "$DIR/config"

echo =====
echo Uploading docker image ${IMAGE_NAME}:${IMAGE_VERSION} ...
echo =====

gcloud docker -- push gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION}

echo
echo =====
echo Updating the deployment with the new image
echo =====
kubectl set image deployment/${DEPLOYMENT_NAME} ${DEPLOYMENT_NAME}=gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_VERSION}
